name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.18.1
      with:
        clangFormatVersion: 14
  build:
    needs: clang-format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DCPACK_PACKAGE_CONTACT="${{ secrets.CONTACT }}" -B build
      - name: Build
        run: cmake --build build
      - name: Run
        run: ./build/ascii-weather-forecast Madrid?2FnQ
      - name: Pack
        working-directory: build
        run: cpack -G "DEB"
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: build/*.deb
